import { SMEProfile, TrustEvent } from '../agent/types';

export const SEEDED_SMES: SMEProfile[] = [
  {
    id: 'sme-amina',
    name: 'Amina Foods',
    sector: 'Food Retail',
    description: 'Speciality wholesale cooking oil and baking supplies based in Nairobi Eastleigh.',
    location: 'Nairobi Eastleigh',
    languages: ['en', 'sw', 'sheng'],
    identity_status: 'verified',
    offer_summary: '20 cartons of vegetable cooking oil (10L each)',
    need_summary: '200 food-grade corrugated packaging boxes',
    trust_events: [
      {
        id: 'te-1',
        sme_id: 'sme-amina',
        event_type: 'completed_exchange',
        outcome: 'confirmed',
        evidence_text: 'Successfully exchanged 15 tins cooking oil with Mama Terry Bakery on time.',
        created_at: '2026-08-14',
      },
      {
        id: 'te-2',
        sme_id: 'sme-amina',
        event_type: 'completed_exchange',
        outcome: 'confirmed',
        evidence_text: 'Supplied pantry provisions for event catering without delays.',
        created_at: '2026-09-02',
      },
      {
        id: 'te-3',
        sme_id: 'sme-amina',
        event_type: 'identity_confirmed',
        outcome: 'verified',
        evidence_text: 'Verified business registration certificate (Eastleigh Chamber).',
        created_at: '2026-07-20',
      },
    ],
  },
  {
    id: 'sme-greenpack',
    name: 'GreenPack KE',
    sector: 'Packaging & Paper',
    description: 'Eco-friendly cardboard containers and food carton manufacturer in Industrial Area.',
    location: 'Nairobi Industrial Area',
    languages: ['en', 'sw'],
    identity_status: 'verified',
    offer_summary: '200 food-grade corrugated packaging boxes',
    need_summary: 'Same-day courier dispatch and delivery across Nairobi',
    trust_events: [
      {
        id: 'te-4',
        sme_id: 'sme-greenpack',
        event_type: 'identity_confirmed',
        outcome: 'verified',
        evidence_text: 'National Business Registry verified registration.',
        created_at: '2026-06-10',
      },
      {
        id: 'te-5',
        sme_id: 'sme-greenpack',
        event_type: 'completed_exchange',
        outcome: 'confirmed',
        evidence_text: 'Delivered 500 pastry boxes to Jirani Cafe.',
        created_at: '2026-08-28',
      },
    ],
  },
  {
    id: 'sme-swiftmove',
    name: 'SwiftMove Couriers',
    sector: 'Logistics & Dispatch',
    description: 'Fleet of 8 motorcycle dispatch riders covering Nairobi County and outskirts.',
    location: 'Nairobi Westlands',
    languages: ['en', 'sw', 'sheng'],
    identity_status: 'verified',
    offer_summary: 'Same-day courier dispatch (up to 5 delivery trips)',
    need_summary: 'Quarterly bookkeeping and tax return preparation',
    trust_events: [
      {
        id: 'te-6',
        sme_id: 'sme-swiftmove',
        event_type: 'completed_exchange',
        outcome: 'confirmed',
        evidence_text: 'Completed 12 on-time logistics drops for PrintLab Kenya.',
        created_at: '2026-08-19',
      },
      {
        id: 'te-7',
        sme_id: 'sme-swiftmove',
        event_type: 'completed_exchange',
        outcome: 'confirmed',
        evidence_text: 'Dispatched urgent parcel run during rain without parcel damage.',
        created_at: '2026-09-11',
      },
    ],
  },
  {
    id: 'sme-ledgerpro',
    name: 'LedgerPro Services',
    sector: 'Professional Bookkeeping',
    description: 'SME financial recordkeeping, KRA returns, and inventory ledger reconciliations.',
    location: 'Nairobi CBD',
    languages: ['en', 'sw'],
    identity_status: 'verified',
    offer_summary: '1 month SME bookkeeping & ledger reconciliation',
    need_summary: '20 cartons cooking oil for staff canteen and catering barter',
    trust_events: [
      {
        id: 'te-8',
        sme_id: 'sme-ledgerpro',
        event_type: 'late_delivery',
        outcome: 'resolved',
        evidence_text: 'Monthly reconciliation delayed by 2 days due to KRA portal outage; successfully rectified.',
        created_at: '2026-07-30',
      },
      {
        id: 'te-9',
        sme_id: 'sme-ledgerpro',
        event_type: 'completed_exchange',
        outcome: 'confirmed',
        evidence_text: 'Setup QuickBooks Chart of Accounts for Eastleigh Butchery.',
        created_at: '2026-08-15',
      },
    ],
  },
  {
    id: 'sme-printlab',
    name: 'PrintLab',
    sector: 'Printing & Signage',
    description: 'Digital printing, carton branding, and commercial brochures in Ngara.',
    location: 'Nairobi Ngara',
    languages: ['en', 'sw'],
    identity_status: 'unverified',
    offer_summary: '100 custom printed promotional cards or box labels',
    need_summary: 'Vector logo design and brochure layout refinement',
    trust_events: [
      {
        id: 'te-10',
        sme_id: 'sme-printlab',
        event_type: 'completed_exchange',
        outcome: 'confirmed',
        evidence_text: 'High quality offset batch for local salon.',
        created_at: '2026-09-01',
      },
    ],
  },
  {
    id: 'sme-studio',
    name: 'Jirani Studio',
    sector: 'Graphic Design',
    description: 'Creative studio specializing in brand identity and social media kits.',
    location: 'Nairobi Kilimani',
    languages: ['en', 'sw', 'sheng'],
    identity_status: 'verified',
    offer_summary: 'Full brand kit & vector graphic design',
    need_summary: '100 printed client showcase postcards',
    trust_events: [
      {
        id: 'te-11',
        sme_id: 'sme-studio',
        event_type: 'completed_exchange',
        outcome: 'confirmed',
        evidence_text: 'Delivered packaging artwork for organic spice startup.',
        created_at: '2026-08-04',
      },
    ],
  },
];
